spring.application.name=citasmedicas
server.port=${SERVER_PORT:8082}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@mibd_high}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:USER_CITAS}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Citas1234567}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:oracle.jdbc.OracleDriver}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
spring.jpa.show-sql=true
spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.OracleDialect}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.jackson.serialization.indent_output=true
