CREATE TABLE citas_medicas (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_paciente VARCHAR2(100) NOT NULL,
    rut_paciente VARCHAR2(20) NOT NULL,
    nombre_medico VARCHAR2(100) NOT NULL,
    especialidad VARCHAR2(100) NOT NULL,
    fecha_cita DATE NOT NULL,
    hora_cita VARCHAR2(5) NOT NULL,
    estado VARCHAR2(30) NOT NULL,
    motivo_consulta VARCHAR2(255) NOT NULL
);

INSERT INTO citas_medicas (
    nombre_paciente,
    rut_paciente,
    nombre_medico,
    especialidad,
    fecha_cita,
    hora_cita,
    estado,
    motivo_consulta
) VALUES (
    'Bastian Ortiz',
    '11111111-1',
    'Dra. Ana Lopez',
    'Medicina General',
    DATE '2026-05-10',
    '10:30',
    'PROGRAMADA',
    'Control general'
);

INSERT INTO citas_medicas (
    nombre_paciente,
    rut_paciente,
    nombre_medico,
    especialidad,
    fecha_cita,
    hora_cita,
    estado,
    motivo_consulta
) VALUES (
    'Carla Henriquez',
    '22222222-2',
    'Dr. Pedro Rojas',
    'Traumatologia',
    DATE '2026-05-11',
    '12:00',
    'PROGRAMADA',
    'Dolor de rodilla'
);

INSERT INTO citas_medicas (
    nombre_paciente,
    rut_paciente,
    nombre_medico,
    especialidad,
    fecha_cita,
    hora_cita,
    estado,
    motivo_consulta
) VALUES (
    'Juan Perez',
    '33333333-3',
    'Dra. Maria Soto',
    'Dermatologia',
    DATE '2026-05-12',
    '15:30',
    'CANCELADA',
    'Control de piel'
);

COMMIT;
